### ISSUE TITLE
Release Files in Git Repository

### ISSUE THREAD

**Issue by emanuelduss** [ozzi-/JWT4B#12]
It's not necessary that you commit the built JAR files into the Git repository, which will get bigger and bigger with every new binary file. GitHub has a extra release feature, where you can upload the built JAR file. You can find it in the release tab: https://github.com/mvetsch/JWT4B/releases

Best wishes,
Mänu ;-)

**Comment by ozzi-** [comment]
https://github.com/mvetsch/JWT4B/releases/tag/1.0 👍
