### ISSUE TITLE
Cant edit JWT?

### ISSUE THREAD

**Issue by dinopio** [ozzi-/JWT4B#15]
Plugin loaded normally
I see the decoded message but there is no way to edit the contents to perform a replay attack.
Im a missing something here?

**Comment by ozzi-** [comment]
Hi Dinopio

I observed this problem to, i presume its the rsyntaxtextarea in combination with how Burp loads extensions during runtime. Somehow the key listeners break.
What helps is closing burp and restarting it again, well for me it works.
Please let me know if that does the trick.

**Comment by dinopio** [comment]
you are right, a restart makes it editable

**Comment by ozzi-** [comment]
cool that it works, ill close the issue (for now, unless i find the reason why this occurs using rsyntaxtextarea)
