### ISSUE TITLE
Feature: add support for azure token position

### ISSUE THREAD

**Issue by mvetsch** [ozzi-/JWT4B#16]
Azure sends JWT tokens in a POST parameter id_token. Implementation of a https://github.com/mvetsch/JWT4B/blob/master/src/app/tokenposition/ITokenPosition.java class should be sufficient to support this.

**Comment by ozzi-** [comment]
Because using standards is overrated. Cool feature idea!

**Comment by ozzi-** [comment]
implemented in 6dd6d5cb255a34e1eee4765e1675b86d01dd648c

@mvetsch  Could you test it? It worked in my faked use case. 
if all is well we might want to consider a pull request for the portswigger guys

**Comment by mvetsch** [comment]
Nice, I will check that on Saturday
