### ISSUE TITLE
Cookie token is not being detected.

### ISSUE THREAD

**Issue by akansc** [ozzi-/JWT4B#18]
I have a latest plugin installed, and "auth-token" in Cookie is not being detected.
Would it be possible to implement something like "custom token name" or something similar, in case we face an application that uses a custom token name?

**Comment by ozzi-** [comment]
Dear akansc
Could you please provide the request in question, please remove all sensitive information.
If not possible the cookie header with a censored jwt should suffice.
JWT4B _should_ recognized all JWTokens regardless of the name. 

Best regards

**Comment by akansc** [comment]
Hello,

As I was preparing an example, I've noticed where the issue is.
It is not the token itself, but its position. If the token is the first or the second cookie - it works. If it's third or later - it is not detected.

For example it is not detected in this header:
`Cookie: a=a;  a=a; auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE;`

But if this token is not the third, but the first or the second one - it works:
`Cookie: a=a; auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE;`

**Comment by ozzi-** [comment]
Thanks for the detailed feedback, ill look into it!

**Comment by ozzi-** [comment]
It passes a new unit test which uses three cookies in one header, creating a pull request at portswigger.

**Comment by akansc** [comment]
I have one more bug related to this issue.
Plugin does not detect the token, if some cookie without a value is provided.

For example, this one does not get detected, because "a" doesn't have any value:
`Cookie: a=; auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE;`

**Comment by ozzi-** [comment]
Done  😅
