### ISSUE TITLE
Improve JSON format

### ISSUE THREAD

**Issue by FranklinYu** [ozzi-/JWT4B#19]
JWT headers are decoded into an object, and each key-value pair is displayed on a single line. However, typically [`x5c` (certificate chain) in the header](https://tools.ietf.org/html/rfc7515#section-4.1.6) contains several elements, so instead of a long

```json
{
  "x5c" : [ "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef", "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef", "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef" ]
}
```

we can do

```json
{
  "x5c" : [
    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  ]
}
``

**Comment by ozzi-** [comment]
Hi Franklin
Thanks for your report, ill see when i find time to fix this.

Note to 
self: The problem is found in ReadableTokenFormat -> jsonBeautify
https://github.com/mvetsch/JWT4B/blob/b2ecd3c026be8bcb410c7399742cdc2931918e4f/src/app/controllers/ReadableTokenFormat.java

**Comment by ozzi-** [comment]
@franklinyu 
Can you please check if this fixes the issue? I compiled you a version so you do not have to. Otherwise feel free to compile on your own.

[jwt4b.jar.zip](https://github.com/mvetsch/JWT4B/files/1421814/jwt4b.jar.zip)

**Comment by FranklinYu** [comment]
Now header and payload are both minified

```text
Headers = {"alg":"HS256","typ":"JWT"}
Payload = {"sub":"1234567890","name":"John Doe","admin":true}
Signature = "TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
```

**Comment by ozzi-** [comment]
please provide the JWT in question

**Comment by FranklinYu** [comment]
```text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```

Got it from <https://jwt.io/>.

**Comment by ozzi-** [comment]
I think i misunderstood you, i thought the JWT was wrongly encoded after editing, but you were just saying the display in the edit view is not properly performed. Now i get it. Let me fix this

**Comment by FranklinYu** [comment]
@ozzi- Sorry to have confused you. Yes, the encoding and decoding is perfectly valid. I just hope to improve the display/look so that it can fit on my screen.

In addition I found that I cannot copy from the "decoded JWT". Not sure if it is intended?

**Comment by ozzi-** [comment]
No worries, i did not properly read your initial message.
I tested it locally, can you confirm the fix?

Concerning your issue with copying, are you referring to which view? The intercept decode? I know that the used highlighting textarea has problems when reloading the plugin jar and not restarting burp. Try closing and opening burp please. 

[jwt4b.jar.zip](https://github.com/mvetsch/JWT4B/files/1423044/jwt4b.jar.zip)

**Comment by FranklinYu** [comment]
Fantastic, this is exactly what I meant.

By the copying issue, I was referring to the top-level tab (the one besides Target, Proxy, Spider, and so on). It has three fields: "Enter JWT", "Enter Secret / Key", and "Decoded JWT". The first two are editable and I can copy from them; it makes sense for the last field to be read-only, but I wish to copy the decoded payload to somewhere else (for example, in a text file).

**Comment by ozzi-** [comment]
Glad to hear!

Oh, burp calls it suite tab. I am able to mark and copy text by using ctrl+c. This is on a debian system.
Can you try restarting burp and using ctrl+c while marking text by mouse?

**Comment by FranklinYu** [comment]
I am able to do that now. Maybe just a glitch, never mind.

**Comment by FranklinYu** [comment]
I think I know why, after some experiments. You were right: every time I load a new extender (from BApp Store or from local file) I need to restart Burp. Otherwise it will always prevent me from copying.

**Comment by ozzi-** [comment]
Yeah i tried to debug it, but the guy developing rsyntaxtextarea could fix this with way less effort than I.

**Comment by dobin** [comment]
I have the same bug with rsyntaxtextarea: Sometimes copy-paste keyboard events just stop working :-(

**Comment by ozzi-** [comment]
Ill investigate this issue, worst case I will look for another lib or use non-highlighted element from Swing directly
