### ISSUE TITLE
CTRL+C support

### ISSUE THREAD

**Issue by ozzi-** [ozzi-/JWT4B#2]
-> getselectedata override

**Comment by ozzi-** [comment]
Done -> fa457bf227baf8f0d27ce7377f576df66fcfe6b7

**Comment by HD421** [comment]
Hello. Can you pls add Command+C support too? Unable to copy at Mac OS X

**Comment by ozzi-** [comment]
Hi @HD421  ill look into this, what macOS version are you using?
Does ctrl work instead of command?

**Comment by HD421** [comment]
Hello @ozzi- , thanks for your time. Unfortunately ctrl isn't working. My MacOS version is High Sierra 10.13.6

**Comment by ozzi-** [comment]
Hi @HD421  
Tested this on a macOS 10.13.6 using CMD+C , +X , +V - works like a charm:
https://raw.githubusercontent.com/ozzi-/ios-web-application-skeleton/master/clipboard.mov

Does copy paste work in other burp apps / burp itself?

Regards

**Comment by HD421** [comment]
Hi @ozzi- 
Yeah, no problem with cmd+c in other burp apps, idk why JWT4B still not work in my case. But thank you anyway. Maybe problem laying in my burp v2.0.9beta

**Comment by ozzi-** [comment]
Oh ill go check on a burp 2.x installation, this might be the problem here

**Comment by ozzi-** [comment]
Mhh I do not have access to burp professional at the moment, so I cannot test the beta.
Can you try it on a Windows / Linux system with v2.0.9? Otherwise ill have to wait until a community edition v2 is released.
