### ISSUE TITLE
JWT detection

### ISSUE THREAD

**Issue by FranklinYu** [ozzi-/JWT4B#20]
Currently if header has `Authorization: Bearer` it would say "JWT detected" (I believe the logic is [here](https://github.com/mvetsch/JWT4B/blob/1.2.1/src/app/tokenposition/AuthorizationBearerHeader.java#L19)), but [RFC 6750](https://tools.ietf.org/html/rfc6750) doesn't require Bearer Token to be JWT (for example some Google API doesn't use JWT as Bearer Token). It might be better to label the request as "JWT detected" only when Bearer Token is valid JWT.

**Comment by ozzi-** [comment]
Yeah you are write, currently only headers starting with "Authorization: Bearer" are considered. Which is rather minimal, i think this code is there since the first prototype. 
It would make more sense to just look through all headers and check if anything in there looks like a JWT. Im on it.

**Comment by ozzi-** [comment]
This should fix the issue, please confirm
https://github.com/mvetsch/JWT4B/blob/2420fb13ca489bbb3f08a8a537f6e906f644fbf1/src/app/tokenposition/AuthorizationBearerHeader.java#L33

Built version with fix:
[jwt4b.jar.zip](https://github.com/mvetsch/JWT4B/files/1430770/jwt4b.jar.zip)

**Comment by FranklinYu** [comment]
Works great! Thank a lot man
