### ISSUE TITLE
REST APIs 

### ISSUE THREAD

**Issue by mvetsch** [ozzi-/JWT4B#22]
Since on REST APIs all requests contain auth-tokens usually this leads to a wall of blue entries in burp: 
![image](https://user-images.githubusercontent.com/4502366/33122692-35014d46-cf78-11e7-8df2-e14b826e01d1.png)

@ozzi- What do you think? Would it make sense to only mark requests with the token in the response? So the plugin just marks the token issuing, instead of every request it is used. 

https://github.com/mvetsch/JWT4B/blob/f3cdc0066c30488fab7e7c097cc0b84871f192cd/src/app/controllers/HighLightController.java#L24

**Comment by ozzi-** [comment]
Well if its the color that is annoying, we could just set a comment and not highlight the entry.
What do you think?

**Comment by mvetsch** [comment]
Or we just color tokens in the response and add the comment for all messages containing a token. That way you still see when the token was issued.
