### ISSUE TITLE
Feedback from Burp Suite Team

### ISSUE THREAD

**Issue by yehgdotnet** [ozzi-/JWT4B#25]
Hi @mvetsch 

i submitted your awesome plugin to Bapp Store.   It is live now.

Burp Suite Team said the following. Please respond to them at support at portswigger.net if you wish.

> Please check everything is ok and let me know of any problems. I wondered, do you really need the main tab. Your extension seems most useful as a Message Editor. People with many extensions installed suffer from tab clutter so if it’s not necessary you could remove.

**Comment by mvetsch** [comment]
Thanks, we already submitted the extension to BApp store earlier. 
The main tab allows to deal with tokens not related to any request, which is quite helpful sometimes.

Is there a better option in the burp suite to offer such functionality?
