### ISSUE TITLE
Allow newlines in secret field

### ISSUE THREAD

**Issue by BastienFaure** [ozzi-/JWT4B#26]
Hi,
I just faced a case in which the signing key contained newlines, which are stripped during paste in the field. That may also be useful in case people want to test the RS256 -> HS256 switch public key as secret.

Thanks!

**Comment by ozzi-** [comment]
Hi @BastienFaure 
Please find the newest release here, you can now user enter in the secret field. https://github.com/mvetsch/JWT4B/releases/tag/1.6

According commit:
https://github.com/mvetsch/JWT4B/commit/6e508c4cc1ac2d9cc9517bc096865d58d6346068

Please test if this works as you would expect, if its ok ill create a pull request for the Bapp Store.

Cheers

**Comment by ozzi-** [comment]
Created pull request for BAPP.
Closing this issue, feel free to reopen though

**Comment by BastienFaure** [comment]
Hi buddy.
Sorry about being lazy I totally forgot to check your update. Graphically this seems to be working but I couldn't validate since I have another bug that prevents me from editing :(

However, I do have another bug: when I want to resign with a random key in the Repeater, the text area for the key becomes huge and hides the rest of the menu:
![jwt4b_bug](https://user-images.githubusercontent.com/5211907/54392813-c313b280-4665-11e9-856c-8a83d737c265.png)

I also see a last corner case when applications have no printable key. Would this a nice improvement being able to select a file containing the key ?
Thanks !

PS: apparently I cannot reopen this issue

**Comment by ozzi-** [comment]
Problem: Resiging with random key in repeater, menu is invisible.
Feature Request: Load key from file

**Comment by ozzi-** [comment]
Hi @BastienFaure 
I think you will enjoy the latest release, sorry it took me this long ;)
https://i.imgur.com/ajtAJRy.png


Cheers
