### ISSUE TITLE
Signature Notification missleading

### ISSUE THREAD

**Issue by GanbaruTobi** [ozzi-/JWT4B#30]
I had the case, where i found the right key of an JWT-Token. I wanted to verify it with this plugin. But since my system time was before the iat, the token was shown as followed:

![JWT-Wrong-Signature-Notification](https://user-images.githubusercontent.com/15239745/62692508-17328100-b9d1-11e9-9b51-4ad6b82b3480.PNG)

It would be helpfull to visualize when a signature was correctly formed/tested. Since other users would get a similar effect when verifying against an expired token. The information of an unmet claim is helpful, but not as important as being able to build correct signatures. From a user point of view it is unclear if the information beneath the red "warning" is extra information or the reason for the red warning. I suggest either to do the coloring only on the Signature/Key part and without the claim testing (Since claims are shown in the bottom corner) or color it like a traffic light and use yellow when a claim is missing but the signature could be verified.

**Comment by ozzi-** [comment]
Hi Tobi
Good input, the red button should be clearer. In this case yellow and more detailed information seems sensible. On my todo list.
Cheers

**Comment by GanbaruTobi** [comment]
I could give it a shot the next two days if you don't mind?

**Comment by ozzi-** [comment]
Pull requests are welcome!

**Comment by ozzi-** [comment]
https://github.com/mvetsch/JWT4B/releases/tag/1.8
