### ISSUE TITLE
Feature: Add jwtKeywords in JWT4B's tab in burp

### ISSUE THREAD

**Issue by slicingmelon** [ozzi-/JWT4B#33]
Hello,

During a recent pentest, the jwt token was being sent via a HTTP header named **jwt**. As such the extension did not recognize it and I was not able to test it. It would be better for users to be able to choose the jwt input sources rather than hardcoing the values in the source. [JOSEPH](https://portswigger.net/bappstore/82d6c60490b540369d6d5d01822bdf61) has a feature like that and it works pretty well.

I am looking forward to see this in JWT4B.

**Comment by ozzi-** [comment]
Hi @slicingmelon 
Good input, I will have to see what is possible, but definitly a good feature to have.
Im not very good with Swing UI's, might just make a json file that configures JWT4b, thoughts on that?

Cheers

**Comment by slicingmelon** [comment]
Hello, yes the values could be saved to a json file. In terms of code, I guess you can have a look at the other extension.

**Comment by ozzi-** [comment]
This commit brings support for config json file https://github.com/mvetsch/JWT4B/commit/c28bfa93c04f94b5cad54e968645a15f19ce1afa 

I decided against a fancy UI, the jwt4b tab has a button "Config" which will open the json file for you, its easy enough for techies ;)

Please help me testing by downloading the latest release 1.9 - https://github.com/mvetsch/JWT4B/releases/tag/1.9 - thanks!

**Comment by ozzi-** [comment]
assuming its good 👍
