### ISSUE TITLE
Bad string constant in app.algorithm.AlgorithmLinker

### ISSUE THREAD

**Issue by eahamberg** [ozzi-/JWT4B#34]
The following final constant is assigned incorrectly:

public static final String publicKeyEnd = "-----BEGIN PUBLIC KEY-----";

This should be:

"-----END PUBLIC KEY-----", naturally.

Also, several certs export with the format "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----"

Thanks for the great extension, BTW.

**Comment by ozzi-** [comment]
Hi @eahamberg 
Thanks for the input, I changed the code accordingly. Ill upload a new release soon, feedback welcome!

Cheers

**Comment by ozzi-** [comment]
https://github.com/mvetsch/JWT4B/releases/tag/1.8.1
