### ISSUE TITLE
burp 2020.1 broke this extension

### ISSUE THREAD

**Issue by royharoush** [ozzi-/JWT4B#37]
in burp 2020.1 you can no longer edit the JWT token.

**Comment by ozzi-** [comment]
@royharoush 
Does this problem persist after restarting burp?
Can you provide any log (Extender Tab)

Note to self:
I might have to replace the rSyntaxTextArea Library

**Comment by ozzi-** [comment]
Hi @royharoush 
Does this fix the problem mentioned? 
[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/4172144/jwt4b.zip)

**Comment by royharoush** [comment]
most of the work i do is in repeater with your extension. 

the version you uploaded here allows editing in repeater, but when you select to "recalculate" siganture", it doesn't actually sends a new signature, just updates the payload. it might have been the case with earlier versios of burp, but i never looked that closely.. 

ill check with the last burp stable and update.

**Comment by ozzi-** [comment]
@royharoush  going to close this issue and continue investigations in #36   :)

**Comment by ozzi-** [comment]
I did some testing, nothing done in the JSON Web Tokens tab is actually reflected in the request, when using the repeater. This is due to getMessage (IMessageEditorTab) not being called in JWTInterceptTabController. Ill do some research and come back to you.

**Comment by ozzi-** [comment]
@royharoush this issue seems to be fixed in burp 2020v4!
https://portswigger.net/burp/releases/professional-community-2020-4
