### ISSUE TITLE
JWT not detected in response body

### ISSUE THREAD

**Issue by bognolo** [ozzi-/JWT4B#40]
The response with the (shortened) JWT that was not detected is 

{
  "found": true,
  "data": {
    "trace": [],
    "errorType": "string",
    "errorMessage": "{\"error\":\"Incorrect xxx\",\"source\":\"xxxx\",\"key\":\"BAD_REQUEST\"}"
  },
  "log": "xxxx',\n      method: 'get',\n      params: [Object],\n      headers: [Object],\n      transformRequest: [Array],\n      transformResponse: [Array],\n      timeout: 0,\n      adapter: [Function],\n      xsrfCookieName: 'XSRF-TOKEN',\n      xsrfHeaderName: 'X-XSRF-TOKEN',\n      maxContentLength: -1,\n      validateStatus: [Function: validateStatus],\n      data: undefined\n    },\n    request: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 6,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      socket: [TLSSocket],\n      connection: [TLSSocket],\n      _header: 'GET xxxxxx?xxxxxx HTTP/1.1\\r\\n' +\n        'Accept: application/json\\r\\n' +\n        'xxxxx: 2e05f7f8-a91f-43a1-b2df-fcde7d142805\\r\\n' +\n        'Authorization: Bearer eyJraWQiO...lYzsTKpibD3Ek7g\\r\\n' +\n        'User-Agent: xxxxx\\r\\n' +\n        'Host: xxxxx\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _onPendingData: [Function: noopPendingOutput],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      insecureHTTPParser: undefined,\n      path: 'xxxx?xxxx',\n      _ended: true,\n      res: [IncomingMessage],\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      _redirectable: [Writable],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype]\n    },\n    data: {\n      httpCode: '400',\n      httpMessage: 'Bad Request',\n      moreInformation: 'Incorrect xxxxx'\n    }\n  },\n  isAxiosError: true,\n  toJSON: [Function]\n}\n2020-04-09T01:50:37.366Z\te1a71ea4-44d8-40cc-9c1c-eddd53dc84ae\tERROR\tInvoke Error \t{\"errorType\":\"Error\",\"errorMessage\":\"{\\\"error\\\":\\\"Incorrect xxxxx\\\",\\\"source\\\":\\\"xxxxx\\\",\\\"key\\\":\\\"BAD_REQUEST\\\"}\",\"stack\":[\"Error: {\\\"error\\\":\\\"Incorrect xxxxx\\\",\\\"source\\\":\\\"xxxxx\\\",\\\"key\\\":\\\"BAD_REQUEST\\\"}\",\"    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)\",\"    at postError (/var/runtime/CallbackContext.js:30:54)\",\"    at callback (/var/runtime/CallbackContext.js:42:7)\",\"    at /var/runtime/CallbackContext.js:105:16\",\"    at /var/task/bb_index.js:63:9\",\"    at Object.module.exports [as client_search] (/var/task/client_search.js:116:5)\",\"    at processTicksAndRejections (internal/process/task_queues.js:97:5)\"]}\nEND RequestId: e1a71ea4-44d8-40cc-9c1c-eddd53dc84ae\nREPORT RequestId: e1a71ea4-44d8-40cc-9c1c-eddd53dc84ae\tDuration: 116.83 ms\tBilled Duration: 200 ms\tMemory Size: 128 MB\tMax Memory Used: 95 MB\t\n",
  "error": "Unhandled",
  "status": 200
}

**Comment by ozzi-** [comment]
Hi @bognolo 
You are receiving a JSON response, containing an array, containing a string starting with " 'Authorization: Bearer eyJraWQiO....' , right?
Currently JWT4B does not scan the response body. This might be a good feature though!

Edit: Oh right, I received a PR at one point implementing this, ill debug

**Comment by ozzi-** [comment]
@bognolo  is that the actual JSON you receive? Its invalid therefore JWT4B won't try to find a token in there.
