### ISSUE TITLE
Extension Modifies Timestamps

### ISSUE THREAD

**Issue by emanuelduss** [ozzi-/JWT4B#42]
Hi Ozzi :)

We discovered an issue while using your extension.

**Issue**

The timestamps are modified by the extension even if the content is not changed.

**Steps to reproduce**

Access a website that uses JWT tokens, e.g. https://www.compass-demo.com/jwt_demo/.

Received JWT:

    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsImV4cCI6MTU5ODM1ODU1NC4zNzQ2MjM1fQ.katJDBB-Yqkdx9u_ua-6OMW1-lNxqHnEiIiRh43cAFQ

Intercept a request containing a JWT and open the "JSON Web Tokens" tab. Forward the JWT without modifying.

    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsImV4cCI6MS41OTgzNTg1NTQzNzQ2MjM1RTl9.katJDBB-Yqkdx9u_ua-6OMW1-lNxqHnEiIiRh43cAFQ

The token is not accepted, because the signature is not valid anymore.

Decoded original token:

    {"role":"user","exp":1598358554.3746235}

Decoded token sent by the extension:

    {"role":"user","exp":1.5983585543746235E9}

So, the extension modifies the timestamp and makes the token invalid, even if it was not modified.

Best,
Mänu

**Comment by ozzi-** [comment]
Ohhhh... this shouldn't happen 
Are you using the latest BAPP version?

edit: this happens in the latest version & is not unique to the "exp" field, tests using "foo" had the same effect on the value

**Comment by ozzi-** [comment]
Bug resides here:
https://github.com/ozzi-/JWT4B/blob/master/src/app/controllers/ReadableTokenFormat.java#L70

This will do some weird things with floats / doubles

**Comment by ozzi-** [comment]
Problem lies here: https://github.com/ozzi-/JWT4B/blob/master/src/app/controllers/ReadableTokenFormat.java#L70
Solution might be WRITE_NUMBERS_AS_STRINGS (https://fasterxml.github.io/jackson-core/javadoc/2.4/com/fasterxml/jackson/core/JsonGenerator.Feature.html)

**Comment by ozzi-** [comment]
Hi @mindfuckup 
Can you confirm it fixed?
I have a JAR here, you can build the latest commit yourself if you prefer
[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/5130599/jwt4b.zip)

Cheers :)

**Comment by emanuelduss** [comment]
Hey Ozzi

I tested the new release https://github.com/ozzi-/JWT4B/releases/tag/1.13 and I can confirm that it is fixed.

THX1K for this very quick fix! Our students will be happy ;-)

LG
Mänu

**Comment by ozzi-** [comment]
Hi Manü
Glad to hear! Happy hacking

PR for Bapp store:
https://github.com/PortSwigger/json-web-tokens/pull/18

Cheers

**Comment by emanuelduss** [comment]
BTW I have to tell you that this extension is so awesome! 🤘🤘🤘 Enabled by default in my Burp Setup 😀. Thanks for creating and still maintaining it!!!
