### ISSUE TITLE
No support for whitespace

### ISSUE THREAD

**Issue by floyd-fuh** [ozzi-/JWT4B#44]
Thanks for this tool. The tool does not honor whitespaces, though. I know, you probably thought nobody would ever do that, but believe me, they do. So simply put, when I chose "do not automatically modify signature" and the header of the original JWT token starts with:

`{"alg":"HS256","typ" : "JWT"` [...]

Then your tool will automatically decode and recreate the JWT token with the following header:

`{"alg":"HS256","typ":"JWT"` [...]

Please note how the spaces before and after the colon are now missing. Obviously, this breaks the signature of the JWT token and makes tests hard.

I'd recommend implementing checks in the tool, that allows recreating a part of the JWT (such as the header) and then compare the base64 generated value with the original value. If they are not the same, then your tool is not recreating the JWT correctly.

Please be also aware that the above example is real life. They managed to have no spaces before and after the colon of the `alg` parameter, but they do have spaces for the `typ` parameter...

**Comment by ozzi-** [comment]
Hi @floyd-fuh 
Thank you for the bug report!
Yeah strange, I did not expect JWT's with spaces...
I fixed "when I chose "do not automatically modify signature" and the header of the original JWT token starts with", however I am still unsure how to handle other cases, as in we want to fiddle around with a JWT and send it containing whitespaces. Any ideas?

I attached a JAR (or feel free to build your own) - can you confirm the bug is gone?

Cheers
[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/5450297/jwt4b.zip)

**Comment by floyd-fuh** [comment]
Well, you can look at the problem from different sides.

In theory the best approach would be to analyze where whitespaces are and remember them and also put them back into the JSON after you're done. Otherwise you lose information and therefore the signature is wrong. I know, this is probably huge pain from a programming perspective. I've seen other weird protocols in practice where weird whitespace mattered byte by byte.

Then the next question is, does the server-side parser accept JSON with a correct signature but the whitespaces missing? The answer is with a high certainty "yes" (because you are going the direction of "normalizing" the JSON to not contain whitespace and therefore the JSON parsers should support that). However, I don't feel comfortable saying such things about JSON, see http://seriot.ch/parsing_json.php . And there could still be the weird programmer who does a static string equals on the JWT header or such.

A more practical approach is the question: Are you modifying at least one bit in the payload? If the answer is yes, then the signature will need recalculation anyway, so in all these cases you can remove the whitespace (if we assume the server accepts that as long as the signature is valid). If you didn't modify a bit in the payload, then you should probably just use all the original values.

So the question: Do you always know if you changed a bit in the JWT?

I'll try the new version later!

**Comment by floyd-fuh** [comment]
Hey @ozzi- 

Unfortunately I have to tell you that with the new version, you made things a lot worse: You are now using the representation you use in your JSON Web Token tab! That means:

```
{
  "alg": 
```

You include newlines and spaces. However, you use your GUI whitespaces, not the original JWT's whitespaces. Please revert the changes.

**Comment by ozzi-** [comment]
Ah silly me, I did not think this through.
Funny enough, there already was a ToDo stating "check if anything was modified, if not return original message".
I implemented a check if any changes were performed in the textarea, if no changes were made and the UI is set to "Do not automatically modify signature", the whitespaces are conserved (this time I checked).

The amount of work involved with remembering white spaces seems pretty huge in comparison to the slight chance that a backend actually validates white spaces (as in next to signature validation, checks their presence) 

Please let me know if this works for you:

[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/5451333/jwt4b.zip)

**Comment by ozzi-** [comment]
Any input @floyd-fuh ?

**Comment by floyd-fuh** [comment]
Hi @ozzi-, sorry for the late reply, actually I don't have access to the environment anymore, sorry I've been really busy. Let's close this for now and if I run into the same/similar issues again, I'll let you know. If you really want to test it, this shouldn't be too hard, just artificially create a token that has a space and make sure the base64 structure doesn't change at all when you look at it in your tool. cheers!
