### ISSUE TITLE
Wrong Signature

### ISSUE THREAD

**Issue by emanuelduss** [ozzi-/JWT4B#45]
Hi ozzi-

I really like this extension and use it a lot but just had some issues while creating signatures with a secret that contains linebreaks.

This is e.g. important in the algorithm confusion attack where you sign your RS256 token using the public key but using the HS265 algorithm.

# Situation

Example JWT:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIiLCJpYXQiOjE2MDU3OTk4MTd9.Spvq4AvnNNd8RFTcZJr2r0re7hSxWi1XBvLSEdpBY2k
```

Decoded:
```
Headers = {
  "alg": "HS256",
  "typ": "JWT"
}

Payload = {
  "foo": "bar",
  "iat": 1605799817
}

Signature = "Spvq4AvnNNd8RFTcZJr2r0re7hSxWi1XBvLSEdpBY2k"
```

# What I want

I get the expected result i previous versions of the extension.

I want to sign it using the following multi line secret (incl. the last linebreak!):
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33TqqLR3eeUmDtHS89qF
3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA
04DDnEFGAf+kDQiNSe2ZtqC7bnIc8+KSG/qOGQIVaay4Ucr6ovDkykO5Hxn7OU7s
Jp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwF
wnxCsU5+UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUE
f0YN3/Q0auBkdbDR/ES2PbgKTJdkjc/rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1W
SwIDAQAB
-----END PUBLIC KEY-----

```

Doing so:
![image](https://user-images.githubusercontent.com/438188/99689828-bc1e8380-2a87-11eb-84e1-a76636c4ae23.png)

Plugin output on stdout:
```
15:41:16.377 | JWT4B says hi!
15:41:34.097 | Recalculating Signature with Secret - 'a
b
'
15:53:36.827 | Recalculating Signature with Secret - '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33TqqLR3eeUmDtHS89qF
3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA
04DDnEFGAf+kDQiNSe2ZtqC7bnIc8+KSG/qOGQIVaay4Ucr6ovDkykO5Hxn7OU7s
Jp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwF
wnxCsU5+UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUE
f0YN3/Q0auBkdbDR/ES2PbgKTJdkjc/rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1W
SwIDAQAB
-----END PUBLIC KEY-----
'

```

Screenshot:
![image](https://user-images.githubusercontent.com/438188/99689886-cc366300-2a87-11eb-8f28-cb4e477e22e0.png)

This works as expected.

Also CyberChef confirms that this is the correct behavior:

![image](https://user-images.githubusercontent.com/438188/99690717-baa18b00-2a88-11eb-92b8-0c4521fbd439.png)

# What I get

In the latest release, the attacks did not work anymore :(.

Performing the same steps as already described.

Plugin output on stdout:
```
15:55:18.704 | JWT4B says hi!
15:55:56.423 | Recalculating Signature with Secret - '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33TqqLR3eeUmDtHS89qF3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA04DDnEFGAf+kDQiNSe2ZtqC7bnIc8+KSG/qOGQIVaay4Ucr6ovDkykO5Hxn7OU7sJp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwFwnxCsU5+UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUEf0YN3/Q0auBkdbDR/ES2PbgKTJdkjc/rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1WSwIDAQAB-----END PUBLIC KEY-----'

```

Screenshot:
![image](https://user-images.githubusercontent.com/438188/99690186-26cfbf00-2a88-11eb-913e-ffaa63d03e63.png)

All linebreaks from the secret input are removed.

This results in a non-working attack :(.

# Issue

- Linebreaks are removed from the secret.

# Solution

- The secret should not be modified by the extension

Can you fix this?

Thanks & LG
Mänu

**Comment by ozzi-** [comment]
Hi Mänu

Thank you for the exemplary issue!
However, do you know if this worked with 1.12? Meaning the perpetrator is in v1.13..

Cheers

**Comment by ozzi-** [comment]
Commit identified
https://github.com/ozzi-/JWT4B/commit/feed19960dc6e45eb0ae3a4f1e5fa11343abb506

**Comment by ozzi-** [comment]
Can you please see if this works? Alternatively feel free to build from the latest commit ;)
[JWT4B.zip](https://github.com/ozzi-/JWT4B/files/5568098/JWT4B.zip)

**Comment by emanuelduss** [comment]
Yayy

![image](https://user-images.githubusercontent.com/438188/99693862-1d485600-2a8c-11eb-9321-a905b76d46b8.png)

Awesome, THX!

**Comment by ozzi-** [comment]
Thanks :) 
https://github.com/ozzi-/JWT4B/releases/tag/1.14
