### ISSUE TITLE
Improper automatic encoding

### ISSUE THREAD

**Issue by henshin** [ozzi-/JWT4B#65]
JWT4B seems to be automatically applying an unicode encoding on some characters as soon as it parses the JWT.
I noticed this on the JWT header. I think it doesn't happen on other parts of the token.
Here's an example. This is how the original header decodes to:
```json
{
  "typ": "JWT",
  "kid": "Z4osLouitTFO+A+xOZ/YcdtlW04=",
  "alg": "RS256"
}
```
This is what JWT4B decodes it to as soon as I switch on the extension on Burp's Repeater:
```json
{
  "typ": "JWT",
  "kid": "Z4osLouitTFO+A+xOZ/YcdtlW04\u003d",
  "alg": "RS256"
}
```
So by simply by switching on the extension, it corrupts the token and makes the request invalid.

**Comment by DolphFlynn** [comment]
This is caused by Gson when pretty printing within ReadableTokenFormat. A simple fix is to use minimal-json to do the pretty printing instead. I'll submit a PR at some point, but in the meantime, this is fixed within a branch (issue65-erroneous-encoding) on my fork.

**Comment by henshin** [comment]
Thanks for investigating and solving this issue 👍
