### ISSUE TITLE
Add hex key support

### ISSUE THREAD

**Issue by virusvfv** [ozzi-/JWT4B#71]
In some cases HMAC key for signing JWT is non-ascii hex string. So we have to support it with JWT4B.
For example U can add in KeyHelper class ( in cleankey or some else method) condition: if key begins from 0x... then key string is been interpreted as hex string.

**Comment by virusvfv** [comment]
I created pull request about it ...

**Comment by ozzi-** [comment]
😎👍
https://github.com/ozzi-/JWT4B/commit/3d30b573738574716463c5c05421fe3d62934c2f
