### ISSUE TITLE
Repeater/Intercept extension interface no longer available

### ISSUE THREAD

**Issue by lanmaster53** [ozzi-/JWT4B#75]
After the latest update, the JWT4B attack interface is no longer available in Repeater or Intercept.

**Comment by virusvfv** [comment]
Hi. Tell please more about this fail. Your burp version, how U installed this extension,  and what error message it gives when loading (in Out / Error tabs in Burp Extender) ???
In my Burp (2022.5.1) release version of jar works well. 
![Screenshot_2022-06-23_00-25-19](https://user-images.githubusercontent.com/41779447/175209270-08a2ae55-4536-4ae1-a75e-f1ea4e87740c.png)

![Screenshot_2022-06-23_00-31-28](https://user-images.githubusercontent.com/41779447/175209580-e510fbf9-9123-43aa-8485-05309dc7855e.png)

**Comment by lanmaster53** [comment]
I am using the package installer version of Burp Suite Pro 2022.5.1 (Stable) and Burp Suite Pro 2022.6 (Early Adopter) on a fully updated Mac OS Cataline 10.15.7. The extension is installed via the BApp store with no errors during loading.

I believe the issue to be the extension's recognition of the JWT. As you can see below, the JWT is sent in the Authorization header without the `Bearer` keyword. Perhaps the extension doesn't see this because of the way you recognize and parse JWTs. These requests aren't highlighted in the proxy history either. I can confirm that the extension does work properly when the `Bearer` keyword is present.

<img width="1471" alt="Screen_Shot_2022-06-23_at_9_39_41_AM-2" src="https://user-images.githubusercontent.com/2516395/175314595-9a081cdb-8763-44d4-89ff-fca8368df970.png">

**Comment by lanmaster53** [comment]
Looking in the JWT4B configuration, it appears that the detection triggers are configurable. I modified them and now it does indeed detect the token. I will close this issue. Thanks!
