### ISSUE TITLE
key,get me key

### ISSUE THREAD

**Issue by lapalipi** [ozzi-/JWT4B#81]
bro,no key.
i need key.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/66582830/209096779-e6402b79-6a6b-4381-b83b-2ea1a5e1e6af.png">

**Comment by ozzi-** [comment]
Hi @lapalipi 
I can't really follow, what key do you need? 😅
Cheers

**Comment by DolphFlynn** [comment]
@lapalipi That looks like one of Burp's inbuilt JWT scan checks in which case the corresponding key is shown within the issue details section.
