### ISSUE TITLE
Support for Deflate compression

### ISSUE THREAD

**Issue by strawp** [ozzi-/JWT4B#82]
I'm testing an app at the moment which I believe uses Azure B2C for its Oauth flow. The header for one of the JWTs contains:

```json
{"kid":"TFeKmaq1SaTlZjv1Kk4HSMLm5ZzliCDVGDvcujZNQQQ","ver":"1.0","zip":"Deflate","ser":"1.0"}
```

Which doesn't get picked up by the plugin. Can this be added?

Thanks!

**Comment by ozzi-** [comment]
Hi @strawp 
I am not sure if I understand you correctly, the response header value is the JSON above?
Cheers

**Comment by strawp** [comment]
The plugin doesn't understand how to decompress and parse the body for this type of compression

**Comment by ozzi-** [comment]
So the JWT is in the body? Can you provide the full HTTP Request / Response (redact sensitive data)?
