### ISSUE TITLE
JSON WEB TOKEN burp plugin  is not working 

### ISSUE THREAD

**Issue by mandp3399** [ozzi-/JWT4B#83]
JSON WEB TOKEN burp plugin  is not working  which signing the token as shown in below screenshot

![image](https://github.com/ozzi-/JWT4B/assets/77928403/546e007e-2884-4b3e-bfcd-63be78b6ac21)

**Comment by mandp3399** [comment]
hi @ozzi- 

could u please look into this issue

**Comment by ozzi-** [comment]
Hi @mandp3399 
I am the maintainer of the other plugin, see screenshot:
![image](https://github.com/ozzi-/JWT4B/assets/7944573/8861b6ff-5be2-4510-80dc-a652fc8ddb81)

For the "correct" repo, please go to https://github.com/RUB-NDS/JOSEPH

Best regards :)
