### ISSUE TITLE
Cookie data HTML not rendered within Intercept tab

### ISSUE THREAD

**Issue by DolphFlynn** [ozzi-/JWT4B#85]
![jwt4b](https://github.com/ozzi-/JWT4B/assets/96876199/eff3aa3e-8a9a-4a9d-92f2-5654825a902a)

HTML rendering has been disabled within Burp extensions and needs to be re-enabled on a per-component basis.

**Comment by ozzi-** [comment]
Sorry didn't see this PR, thanks a bunch!

**Comment by ozzi-** [comment]
https://github.com/ozzi-/JWT4B/commit/950b30719500b55cd6dddfdb3f68818ee2a2db21

**Comment by ozzi-** [comment]
https://github.com/ozzi-/JWT4B/releases/tag/2.4

**Comment by ozzi-** [comment]
Live on BAPP store too now :)
