### ISSUE TITLE
Can't recognize jwt in http header

### ISSUE THREAD

**Issue by wanxia123** [ozzi-/JWT4B#93]
Unable to recognize the jwt content present in the custom http header, I don't know if it's a mistake in my configuration or something else, the screenshot is as follows
![Snipaste_2024-08-12_11-04-07](https://github.com/user-attachments/assets/3913cabc-ed50-4cf7-87a8-b88f85706a0b)

**Comment by ozzi-** [comment]
Good point, I am currently checking any header that has a value starting with bearer, this one is lacking. I will change the code accordingly, isn't quite standard to transport the JWT like this but seems to be used

**Comment by ozzi-** [comment]
Hi @wanxia123 
Feel free to use https://github.com/ozzi-/JWT4B/releases/tag/2.7 until Portswigger will release 2.7 :)
Thanks for the bug report

**Comment by ozzi-** [comment]
Has been released on the BAPP store
